syntax on
set cursorline
highlight CursorLine ctermbg=239
set background=dark
set statusline=%F%m%r%h%w\ [ENCODE=%{(&fenc!=''?&fenc:&enc)}]\ [FORMAT=%{&ff}]\ [TYPE=%Y]\ [POS=%04l,%04v][%p%%]\ [LEN=%L]
set laststatus=2

highlight statusline   term=NONE cterm=NONE guifg=red ctermfg=gray ctermbg=red
highlight statuslinenc term=NONE cterm=NONE guifg=red ctermfg=gray ctermbg=black

set noautoindent
set expandtab
set tabstop=4
set nu
